services:

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "4443:443"
    restart: on-failure
    secrets:
      - ssl_key
      - ssl_crt

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "9000"
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$DATA_WP_DIR'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$DATA_DB_DIR'

secrets:
  ssl_key:
    file: "../$SECRET_KEY"
  ssl_crt:
    file: "../$SECRET_CRT"

networks:
  inception:
    name: inception
    driver: bridge
